### ISSUE TITLE
Backtrace always shows xl_sub_form_screen.rb:40

### ISSUE THREAD

**Issue by andrewhavens** [bmichotte/ProMotion-XLForm#12]
Just upgraded to 0.0.10 and I am still having this issue. Not sure how this is happening, but every time I have an error in my app, and I expect to see the backtrace be related to the code that was executed, instead it shows `xl_sub_form_screen.rb:40` on every line:

```
2015-09-25 08:02:10.993 MyApp[41828:7545129] xl_sub_form_screen.rb:40:in `block in parse_relationships_for_instance:': can't convert String into Integer (TypeError)
    from xl_sub_form_screen.rb:40:in `parse_relationships_for_instance:'
    from xl_sub_form_screen.rb:40:in `parse_included:'
    from xl_sub_form_screen.rb:40:in `parse_collection:'
    from xl_sub_form_screen.rb:40:in `block in all'
    from xl_sub_form_screen.rb:40:in `block in request:'
```

None of this code has anything to do with PM-XLForm except that it is showing up in the backtrace.

**Comment by andrewhavens** [comment]
Just upgraded to RubyMotion 4.4 which mentioned the following:

> [iOS] Fixed a bug where line numbers were not properly symbolicated in exceptions raised in an iOS 9 app.

I'm guessing this was the cause of this error and am assuming RM 4.4 fixes this issue.

**Comment by bmichotte** [comment]
Do you still have this backtrace or RM 4.4 solved the issue ?

**Comment by andrewhavens** [comment]
I'm pretty sure 4.4 solved this issue. I haven't seen it in a while.

**Comment by bmichotte** [comment]
Ok, closing the issue so. Reopen it if needed !
