### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by MOPineyro** [bmichotte/ProMotion-XLForm#26]
The gem compiles fine on my machine running xcode 7.1.1 but when attempting to use travis CI I get `Undefined symbols for architecture i386` errors. In my .travis.yml I specify `osx_image: xcode7.1`. Anyone having a similar issue  and find a solution?

xcode build info from travis :

```
MacOSX10.11.sdk - OS X 10.11 (macosx10.11)
SDKVersion: 10.11
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
PlatformVersion: 1.1
PlatformPath: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
ProductBuildVersion: 15A278
ProductCopyright: 1983-2015 Apple Inc.
ProductName: Mac OS X
ProductUserVisibleVersion: 10.11
ProductVersion: 10.11
```

**Comment by bmichotte** [comment]
I have the exact same error https://travis-ci.org/bmichotte/ProMotion-XLForm and did not yet managed to find why :/ 

edit: in fact, no, this is not the same error...

**Comment by bmichotte** [comment]
you could (maybe) get a hint if you add --trace in your rake spec arg

**Comment by markrickert** [comment]
I'm was getting this issue locally when compiling my RubyMotion project yesterday. I ran `rake --trace` and it appeared that one of the pods that it was compiling _BEFORE_ XLForm had an error in compilation making the issue a red herring :fish:.

I fixed the error in the pod i was referencing from a branch on git and it compiled without issue.

**Comment by michaeljkchoi** [comment]
~~I'm having this issue when using the Facebook SDK~~

**EDIT**: Sorry, spoke too soon.  Just needed a rake clean:all and rake pod:install
