### ISSUE TITLE
Problem adding .on(:touch) event to form footer

### ISSUE THREAD

**Issue by eliduke** [bmichotte/ProMotion-XLForm#30]
On my `LoginScreen` I have a footer on the form that says "Forgot your username or password?" and I would like that to be tappable. I tried finding the last `UITableViewHeaderFooterView` and putting a `.on(:touch)` right on it.

```
find(UITableViewHeaderFooterView).last.on(:touch) do
  mp "forgot something?"
end
```

But, I keep getting this error:

```
events.rb:92:in `block in on:': [RMQ Error]  Event already exists on this object: touch. Remove first, using .off (RuntimeError)
```

I was not expecting an event to be on that footer, so first I checked to make sure that I was grabbing the right view by doing this:

```
find(UITableViewHeaderFooterView).last.get.contentView.backgroundColor = color.red
```

That correctly turns the whole footer view red. So, I've got the right view. So, next I tried turning the mystery event off first like this:

```
find(UITableViewHeaderFooterView).last.off
find(UITableViewHeaderFooterView).last.on(:touch) do
  mp "forgot something?"
end
```

But I get this error:

```
event.rb:124:in `remove': undefined method `removeTarget:action:forControlEvents:' for #<UITableViewHeaderFooterView:0x11466f8a0> (NoMethodError)
```

The weird thing is that if I remove the setting of the event and just do this:

```
find(UITableViewHeaderFooterView).last.off
```

I do NOT get an error. Weird stuff happening. Any thoughts?

**Comment by bmichotte** [comment]
To be honest, I do not have a single idea of what happens !
But, I find that you can use the following

``` ruby
rmq.wrap(find(UITableViewHeaderFooterView).last.get.contentView).on(:tap) do 
     puts 'hello'
end
```

This grabs the `contentView` of your `UITableViewHeaderFooterView`, wrap it onto a `rmq` object and then assign the `on(:tap)` event on it, and it seems to work

**Comment by eliduke** [comment]
I tried doing that in `on_appear` and I'm getting the same error.

```
events.rb:92:in `block in on:': [RMQ Error]  Event already exists on this object: tap. Remove first, using .off (RuntimeError)
```

**Comment by eliduke** [comment]
Any ideas? Any one?

**Comment by bmichotte** [comment]
It's difficult to say without being able to reproduce :/. Do you have the same error with `on_load` ? 

I'll look tomorrow (it's 10pm here now) if it's possible to "trace" the events already registered.

**Comment by bmichotte** [comment]
This is what I tried : on https://github.com/infinitered/rmq/blob/master/motion/ruby_motion_query/events.rb#L90 I added 

``` ruby
mp "Adding #{event} to #{selected}"
mp caller
```

The result is the following

```
> "Adding tap to [#<_UITableViewHeaderFooterContentView:0x110670f20>]"
[
  "home_screen.rb:35:in `on_appear'",
  "screen_module.rb:53:in `view_did_appear:'",
  "ui_view_controller.rb:95:in `viewDidAppear:'",
  "xl_form_view_controller.rb:24:in `viewDidAppear:'"
]
"Adding tap to [#<_UITableViewHeaderFooterContentView:0x110670f20>]"
[
  "home_screen.rb:35:in `on_appear'",
  "screen_module.rb:53:in `view_did_appear:'",
  "xl_form_view_controller.rb:25:in `viewDidAppear:'"
]
```

So it seems that the `on_appear` is called twice. As a workaround, you can use 

``` ruby
def on_appear
    rmq.wrap(find(UITableViewHeaderFooterView).last.get.contentView).off.on(:tap) do
        puts 'hello'
    end
end
```

Notice the `off` before the `on`.

Could you try this, I'll check why it's called twice

**Comment by bmichotte** [comment]
Ok, this should be corrected.
You can use `gem "ProMotion-XLForm", github: 'bmichotte/ProMotion-XLForm'` for now

**Comment by eliduke** [comment]
Thanks for your help with this! I was able to use your workaround for now, but I'm having another weird problem.

I am using this `.on(:tap)` event on some "forgot your password?" footer text on my `LoginScreen`. When I am logged out and `rake` the app, it loads the login screen just fine and I am able to click that footer text and it responds and all is well. From there I can login, but then if I logout of the app, which then opens the login screen again, I am getting this error:

```
login_screen.rb:6:in `on_appear': undefined method `contentView' for nil:NilClass (NoMethodError)
```

From there if I re-rake the app, it loads up just fine. It's like, that method works on initial rake and loading of the login screen, but if I try to load it from within the app by logging out, it fails. Can you think of a reason why rmq would have a problem finding that view in that case?
