### ISSUE TITLE
Add support for autofocus when a PM::XLFormScreen is loaded

### ISSUE THREAD

**Issue by admpsktt** [bmichotte/ProMotion-XLForm#33]
My [previous issue](https://github.com/bmichotte/ProMotion-XLForm/issues/32) reminded me that it would be nice if, when a `PM::XLFormScreen` is loaded, a `cell` could be selected for autofocus.

Again, though, is there an option I'm missing for an item in my `cells` array that achieves this?

**Comment by admpsktt** [comment]
This issue can be closed; I re-visited this today and came up with [a solution](https://github.com/bmichotte/ProMotion-XLForm/issues/32#issuecomment-171964844).

**Comment by bmichotte** [comment]
I reopen your issue to implement this feature very soon

**Comment by admpsktt** [comment]
:+1:

**Comment by bmichotte** [comment]
Simple use the `auto_focus: true` option of the `form_option`, see [class options](https://github.com/bmichotte/ProMotion-XLForm#class-options)
