### ISSUE TITLE
Textarea vs textview - no error messaging.

### ISSUE THREAD

**Issue by MikeCaputo** [bmichotte/ProMotion-XLForm#35]
I recently spent a chunk of time troubleshooting a crash with no error messaging. I was attempting to use `textarea` instead of `textview` when defining a form_data's cell type. Upon trying to render the screen, the whole app would crash with no error message. Some kind of messaging might be helpful here. Maybe I'll submit a PR.

**Comment by bmichotte** [comment]
Will you submit a PR or do you want I do it ?
