### ISSUE TITLE
XLFormScreen background_color

### ISSUE THREAD

**Issue by eliduke** [bmichotte/ProMotion-XLForm#36]
I can't seem to change the background color of a form screen with RMQ. I have tried setting this in the form screen stylesheet and in the application stylesheet. Nothing seems to work.

```
def root_view(st)
  st.background_color = color.white
end
```

It just does the sorta standard light gray background color instead. Is there some sort of hard-coded background color being set for a form screen?

**Comment by bmichotte** [comment]
``` ruby
def form_view(st)
end
```

is now available !
