### ISSUE TITLE
Question: How do I create a picker with Items to select from?

### ISSUE THREAD

**Issue by uksa** [bmichotte/ProMotion-XLForm#38]
I want to create a custom picker with items to select, however I cannot find an example or figure out from the code how to approach.

Is there some further documentation you can point me to; to create this feature.

**Comment by uksa** [comment]
I went with :selector_picker_view_inline as its a great way to create your picker values in the form.

**Comment by bmichotte** [comment]
I was answering with this, glad to see you find it first ;)
