### ISSUE TITLE
localizing buttons actions

### ISSUE THREAD

**Issue by soyoh** [bmichotte/ProMotion-XLForm#48]
Hi,
I'm translating my app into several languages, but i noticed that some "system" buttons generated by XLForm are not translated, is there a way to do this? (sorry if this is a silly question...)

i'd like to translate "done", "save", "choose from library" etc.. that seems to stay the same no matter which language the devices is.

Thank you!

**Comment by soyoh** [comment]
Seems that just adding the `Localizable.strings` for the language i want to translate solves the problem.

**Comment by bmichotte** [comment]
I love when issues auto-solve themselves :D
