### ISSUE TITLE
Styling the form with rmq

### ISSUE THREAD

**Issue by uksa** [bmichotte/ProMotion-XLForm#49]
I've attempted to style the form using req, however I can't seem to figure out how to do it.

class MyScreen < PM::XLFormScreen

```
  def on_load
    rmq.stylesheet = MyStylesheet
  end
```

StyleSheet

```
  def form_view(st)
    st.background_color = UIColor.greenColor
  end
```

However no styling is applied, looking at the code, I need to get **if self.class.respond_to?(:rmq_style_sheet_class) && self.class.rmq_style_sheet_class** to be true, however I can't figure out how to achieve this. Please help :)

**Comment by bmichotte** [comment]
what about 

``` ruby
class MyScreen < PM::XLFormScreen
  stylesheet MyStylesheet
end
```

**Comment by uksa** [comment]
**undefined method `stylesheet'**

Do I need to include some reference to req stylesheet, I tried include RubyMotionQuery however it made no difference and I still got an undefined method.

**Comment by grimmwerks** [comment]
uksa - are you using redpotion?

**Comment by grimmwerks** [comment]
Just to let you know -- I'm using redpotion; I've got a form_data PM::XLFormScreen and using  stylesheet MyClass as referenced above, and

```
  def form_view(st)
    st.background_color = color.green
  end
```

worked exactly as it should.  If you _are_ using redpotion try  calling 'rake newclear' and see if that cleans everything up?

**Comment by uksa** [comment]
Yep that was the issue, I'm using ruby_motion_query gem instead of redpotion, it works now. Thanks for the support.
