### ISSUE TITLE
can't convert Class into String after newclear

### ISSUE THREAD

**Issue by nathanbrakken** [bmichotte/ProMotion-XLForm#50]
After rake newclear, I get this error

```
Terminating app due to uncaught exception 'TypeError', reason: 'xl_form_screen.rb:97:in `valid?': can't convert Class into String
```

It appears that the pod is updated and no longer returns an array?

**Comment by nathanbrakken** [comment]
I wonder if setting the version of XLForm in lib/ProMotion-XLForm.rb would help for stability.

```
pod 'XLForm', '3.1.1'
```

**Comment by jeanmartin** [comment]
Same problem here. XLForm 3.2.0, 3.1.0, no difference. Did you find a solution?

**Comment by jeanmartin** [comment]
So, 3.1.1 does indeed work (but has some other issues...)

**Comment by andrewhavens** [comment]
@jeanmartin What other issues? @nathanbrakken Have you run into any issues using 3.1.1. Do you think you could submit a pull request for this change? I can help you with that.

**Comment by nathanbrakken** [comment]
@andrewhavens I haven't come across any other issues yet.
