### ISSUE TITLE
Setting 'value' for ':date' cell causes errors

### ISSUE THREAD

**Issue by michaeljkchoi** [bmichotte/ProMotion-XLForm#8]
When you set a default value of a date field, you get an
Error:

```
xl_sub_form_screen.rb:40:in `==:': undefined method `year' for true:TrueClass (NoMethodError)
```

My code:

``` ruby
def form_data
  ...
  {
    name: :the_future,
    title: "The Future",
    type: :date,
    value: NSDate.new.delta(days: 1),
    properties: {
      min: NSDate.new.delta(days: 1),
      max: NSDate.new.delta(days: 31)
    }
  }
  ...
end
```

**Comment by bmichotte** [comment]
Weird, can't reproduce... 

![capture d ecran 2015-09-24 a 20 25 16](https://cloud.githubusercontent.com/assets/235510/10082512/6e1da5a8-62fa-11e5-9f98-ac0d469e4840.png)

What's ios version are you targetting, is this iphone or ipad ? 
Do you also get the error if you use `:date_inline`  instead of `:date`

**Comment by michaeljkchoi** [comment]
Targeting iOS 8.4 for iPhone.
I get the error for both `:date_inline` and `:date`

**Comment by bmichotte** [comment]
Could I get your Gemfile and app.pods to get the same "env" than you ?

What's the context of this `form_data` ? (is this a `PM::XLFormScreen`, a `PM::XLSubFormScreen`, other ?)

**Comment by bmichotte** [comment]
Looks like there's something strange happening... this looks like similar to #7, with "something strange happens within this class"

**Comment by michaeljkchoi** [comment]
Yeah, maybe it's the same issue.  I'll try this using a simulator running iOS 8.4 (using 9.0, deployment_target 8.4).

`form-data` is a `PM::XLFormScreen`

``` ruby
# Gemfile
source "https://rubygems.org"

gem "rake"

gem "bubble-wrap", "~> 1.8.0"
gem "afmotion"
gem "motion-kit"
gem "sweet-kit"
gem "sugarcube", require: ["sugarcube-animations", "sugarcube-nsdate"]
gem "motion-support"

gem "ProMotion", "~> 2.4.0"
gem "ProMotion-XLForm"
gem "ProMotion-menu"
```

``` ruby
# Rakefile
app.pods do
  pod "Stripe"
  pod "Mixpanel"
  pod "Harpy" 
end
```

**Comment by michaeljkchoi** [comment]
I still get the issue with a simulator running iOS 8.4.  I'm on RubyMotion 4.1 at the moment (haven't upgraded to RM 4.2 yet).

**Comment by bmichotte** [comment]
Could you change your Gemfile to 
`gem "ProMotion-XLForm", github: 'bmichotte/ProMotion-XLForm'` (and bundle it)
and see if it fix your issue ?

**Comment by michaeljkchoi** [comment]
Works! Thanks @bmichotte!!!!

**Comment by bmichotte** [comment]
:+1:

**Comment by bmichotte** [comment]
I'm waiting for some other issues before releasing a new version
