### ISSUE TITLE
ProMotion-Form's 'dismiss_keyboard' method

### ISSUE THREAD

**Issue by michaeljkchoi** [bmichotte/ProMotion-XLForm#9]
Is `dismiss_keyboard` necessary in ProMotion-XLForm?

As per PM-Form's README

> #### dismiss_keyboard
> 
> Dismisses the keyboard. Note that you may need to call this before `render_form` to ensure that you capture the input from the currently focused form element.

I have the code on a fork, if you feel this is necessary/provides a cleaner convenience method.

``` ruby
# lib/ProMotion/XLForm/xl_form_screen.rb

def dismiss_keyboard
  self.view.endEditing true
end
```

**Comment by bmichotte** [comment]
Feel free to PR ;)

**Comment by bmichotte** [comment]
closed by https://github.com/bmichotte/ProMotion-XLForm/pull/10
